import { ExchangeIconEtherium, } from '../../../../../assets/images';

export const exchangeList = [
    'BTC',
    'ETH',
    'BNB',
    'XRP',
    'TRX',
    'USDT',
    'BCH',
];
export const sampleExchangeList = [
    {
        id: 1,
        icon: ExchangeIconEtherium,
        name: 'Etherium ',
        abrevation: 'ETH',
        difference: '$27,664.06',
        rise: false,
        percentage: '7.75%',
        amount: '$523,325,533,763.25',
    },
    {
        id: 2,
        icon: ExchangeIconEtherium,
        name: 'Etherium ',
        abrevation: 'ETH',
        difference: '$27,664.06',
        rise: false,
        percentage: '7.75%',
        amount: '$523,325,533,763.25',
    },
    {
        id: 3,
        icon: ExchangeIconEtherium,
        name: 'Etherium ',
        abrevation: 'ETH',
        difference: '$27,664.06',
        rise: false,
        percentage: '7.75%',
        amount: '$523,325,533,763.25',
    },
    {
        id: 4,
        icon: ExchangeIconEtherium,
        name: 'Etherium ',
        abrevation: 'ETH',
        difference: '$27,664.06',
        rise: true,
        percentage: '7.75%',
        amount: '$523,325,533,763.25',
    },
    {
        id: 5,
        icon: ExchangeIconEtherium,
        name: 'Etherium ',
        abrevation: 'ETH',
        difference: '$27,664.06',
        rise: false,
        percentage: '7.75%',
        amount: '$523,325,533,763.25',
    },
    {
        id: 6,
        icon: ExchangeIconEtherium,
        name: 'Etherium ',
        abrevation: 'ETH',
        difference: '$27,664.06',
        rise: false,
        percentage: '7.75%',
        amount: '$523,325,533,763.25',
    },
    {
        id: 7,
        icon: ExchangeIconEtherium,
        name: 'Etherium ',
        abrevation: 'ETH',
        difference: '$27,664.06',
        rise: false,
        percentage: '7.75%',
        amount: '$523,325,533,763.25',
    },
];
