import { number, string } from "yup/lib/locale"

export interface iBasicInfo {
    apartment_name: string,
    country: string,
    state: string,
    lga: string,
    address: string,
    email: string,
    phone: string,
    website: string,
}

export interface iAdvancedInfo {
    single: number,
    suites: number,
    executive: number,
    double_chambers: number,
    description: string,
    bedrooms: number,
    bathrooms: number,
    parking: number,
    pool: number,
    bathtube: number,
    bidet: number,
    body_soap: number,
    cleaning_products: number,
    hot_water: number,
    bed_linens: number,
    clothing_storage: number,
    drying_rack: number,
    essentials: number,
    extra_pillows: number,
    free_dryer: number,
    free_washer: number,
    hangers: number,
    iron: number,
    darkening_shades: number,
    archade_games: number,
    bluetooth: number,
    reading: number,
    game_console: number,
    ping_pong_table: number,
    pool_table: number,
    tv: number,
    ac: number,
    fans: number,
    monoxide_alarm: number,
    fire_extinguisher: number,
    first_aid_kit: number,
    security_cameras: number,
    smoke_alarm: number,
    dedicated_workspace: number,
    wifi: number,
    bbq_grill: number,
    outdoor_dining: number,
    outdoor_furniture: number,
    patio_balcony: number,
    backyard_fenced: number,
    carpot: number,
    street_parking: number,
    private_pool: number,
    lockbox: number,
    self_checkin: number,
    images: File[]
}

export const sampleBasicInfo: iBasicInfo = {
    apartment_name: '',
    country: '',
    state: '',
    lga: '',
    address: '',
    email: '',
    phone: '',
    website: '',
}

export const sampleAdvancedInfo: iAdvancedInfo = {
    single: 0,
    suites: 0,
    executive: 0,
    double_chambers: 0,
    description: '',
    bedrooms: 1,
    bathrooms: 1,
    parking: 0,
    pool: 0,
    bathtube: 0,
    bidet: 0,
    body_soap: 0,
    cleaning_products: 0,
    hot_water: 0,
    bed_linens: 0,
    clothing_storage: 0,
    drying_rack: 0,
    essentials: 0,
    extra_pillows: 0,
    free_dryer: 0,
    free_washer: 0,
    hangers: 0,
    iron: 0,
    darkening_shades: 0,
    archade_games: 0,
    bluetooth: 0,
    reading: 0,
    game_console: 0,
    ping_pong_table: 0,
    pool_table: 0,
    tv: 0,
    ac: 0,
    fans: 0,
    monoxide_alarm: 0,
    fire_extinguisher: 0,
    first_aid_kit: 0,
    security_cameras: 0,
    smoke_alarm: 0,
    dedicated_workspace: 0,
    wifi: 0,
    bbq_grill: 0,
    outdoor_dining: 0,
    outdoor_furniture: 0,
    patio_balcony: 0,
    backyard_fenced: 0,
    carpot: 0,
    street_parking: 0,
    private_pool: 0,
    lockbox: 0,
    self_checkin: 0,
    images: []

}