 
 
 export const routeConstants = {
     all: '*',
     home: '/',
     home2: 'home',
     about: 'about',
     login: 'log-in',
     signup: 'sign-up',
     offers: 'offers',
     skyflexPay: 'skyflex-pay',
     skyRewards: 'sky-rewards',
     travelOnCredit: 'travel-on-credit',
     terms: 'terms',
     privacyPolicy: 'privacy-policy',
     careers: 'careers',
     contact: 'contact',
     help: 'help',
     partners: 'partners',
     faq: 'faq',

     flights: 'flights',
     stays: 'stays',
     bookRides: 'book-rides',
     rewards: 'rewards',
     deals: 'deals',
     explore: 'explore',
     travelInfo: 'travel-info',
     flightTracker: 'flight-tracker',
     myBookings: 'my-bookings',
     feedBack: 'feed-back',
     industryNews: 'news',
 };