 
 
 export const routeConstants = {
     all: '*',
     home: '/',
     home2: 'home',
     about: 'about',
     login: 'log-in',
     signup: 'sign-up',
     verfyEmail: 'verfy-email',
     requestPassword: 'request-password',
     updatePassword: 'update-password',
     offers: 'offers',
     skyflexPay: 'skyflex-pay',
     skyRewards: 'sky-rewards',
     travelOnCredit: 'travel-on-credit',
     terms: 'terms',
     privacyPolicy: 'privacy-policy',
     careers: 'careers',
     contact: 'contact',
     help: 'help',
     partners: 'partners',
     faq: 'faq',

     profile: 'profile',
     flights: 'flights',
     flightPreview: 'flight-Preview',
     flightBooking: 'flight-booking',
     flightDetails: 'flight-details',
     stays: 'stays',
     stayPreview: 'stay-Preview',
     stayBooking: 'stay-booking',
     stayDetails: 'stay-details',
     bookRides: 'book-rides',
     rewards: 'rewards',
     deals: 'deals',
     explore: 'explore',
     travelInfo: 'travel-info',
     flightTracker: 'flight-tracker',
     myBookings: 'my-bookings',
     feedBack: 'feed-back',
     industryNews: 'news',
 };